spring:
  application:
    name: FitWeek-Backend

  datasource:
    # AWS RDS endpoint will be injected here
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fitweek_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:my_db_fitWeek}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Custom property for our AI microservice
ai:
  service:
    # AWS ECS/App Runner address will be injected here
    url: ${AI_SERVICE_URL:http://localhost:8000}